<?php
return array (
  'ZC_SITE_TURNOFF' => false,
  'ZC_BLOG_HOST' => 'http://localhost/ZPHP/',
  'ZC_BLOG_NAME' => 'mysite',
  'ZC_BLOG_SUBNAME' => 'Good Luck To You!',
  'ZC_BLOG_THEME' => 'default',
  'ZC_BLOG_CSS' => 'default',
  'ZC_BLOG_COPYRIGHT' => 'Copyright Your WebSite.Some Rights Reserved.',
  'ZC_BLOG_LANGUAGE' => 'zh-CN',
  'ZC_BLOG_LANGUAGEPACK' => 'SimpChinese',
  'ZC_DATABASE_TYPE' => 'mysqli',
  'ZC_SQLITE_NAME' => '',
  'ZC_SQLITE_PRE' => 'zbp_',
  'ZC_MYSQL_SERVER' => 'localhost',
  'ZC_MYSQL_USERNAME' => 'root',
  'ZC_MYSQL_PASSWORD' => '',
  'ZC_MYSQL_NAME' => 'ZPHP',
  'ZC_MYSQL_CHARSET' => 'utf8',
  'ZC_MYSQL_PRE' => 'zbp_',
  'ZC_MYSQL_ENGINE' => 'MyISAM',
  'ZC_MYSQL_PORT' => '3306',
  'ZC_MYSQL_PERSISTENT' => false,
  'ZC_USING_PLUGIN_LIST' => 'UEditor',
  'ZC_YUN_SITE' => '',
  'ZC_DEBUG_MODE' => false,
  'ZC_DEBUG_MODE_STRICT' => false,
  'ZC_DEBUG_MODE_WARNING' => true,
  'ZC_DEBUG_MODE_FULL' => false,
  'ZC_BLOG_CLSID' => '53b2c1f07e99b220755945',
  'ZC_TIME_ZONE_NAME' => 'Asia/Shanghai',
  'ZC_UPDATE_INFO_URL' => 'http://update.zblogcn.com/info/',
  'ZC_PERMANENT_DOMAIN_ENABLE' => false,
  'ZC_MULTI_DOMAIN_SUPPORT' => false,
  'ZC_BLOG_PRODUCT' => 'Z-BlogPHP',
  'ZC_BLOG_VERSION' => '1.3 Wonce Build 140614',
  'ZC_BLOG_PRODUCT_FULL' => 'Z-BlogPHP 1.3 Wonce Build 140614',
  'ZC_BLOG_PRODUCT_HTML' => '<a href="http://www.zblogcn.com/" title="RainbowSoft Z-BlogPHP" target="_blank">Z-BlogPHP</a>',
  'ZC_BLOG_PRODUCT_FULLHTML' => '<a href="http://www.zblogcn.com/" title="RainbowSoft Z-BlogPHP" target="_blank">Z-BlogPHP 1.3 Wonce Build 140614</a>',
  'ZC_COMMENT_TURNOFF' => true,
  'ZC_COMMENT_VERIFY_ENABLE' => false,
  'ZC_COMMENT_REVERSE_ORDER' => false,
  'ZC_VERIFYCODE_STRING' => 'ABCDEFGHKMNPRSTUVWXYZ123456789',
  'ZC_VERIFYCODE_WIDTH' => 90,
  'ZC_VERIFYCODE_HEIGHT' => 30,
  'ZC_VERIFYCODE_FONT' => 'zb_system/defend/arial.ttf',
  'ZC_DISPLAY_COUNT' => 5,
  'ZC_SEARCH_COUNT' => 25,
  'ZC_PAGEBAR_COUNT' => 10,
  'ZC_COMMENTS_DISPLAY_COUNT' => 100,
  'ZC_DISPLAY_SUBCATEGORYS' => false,
  'ZC_RSS2_COUNT' => 10,
  'ZC_RSS_EXPORT_WHOLE' => true,
  'ZC_MANAGE_COUNT' => 50,
  'ZC_EMOTICONS_FILENAME' => 'face',
  'ZC_EMOTICONS_FILETYPE' => 'png|gif|jpg',
  'ZC_EMOTICONS_FILESIZE' => '16',
  'ZC_UPLOAD_FILETYPE' => 'jpg|gif|png|jpeg|bmp|psd|wmf|ico|rpm|deb|tar|gz|sit|7z|bz2|zip|rar|xml|xsl|svg|svgz|doc|docx|ppt|pptx|xls|xlsx|wps|chm|txt|pdf|mp3|avi|mpg|rm|ra|rmvb|mov|wmv|wma|swf|fla|torrent|apk|zba',
  'ZC_UPLOAD_FILESIZE' => 2,
  'ZC_USERNAME_MIN' => 3,
  'ZC_USERNAME_MAX' => 50,
  'ZC_PASSWORD_MIN' => 8,
  'ZC_PASSWORD_MAX' => 20,
  'ZC_EMAIL_MAX' => 50,
  'ZC_HOMEPAGE_MAX' => 100,
  'ZC_CONTENT_MAX' => 1000,
  'ZC_ARTICLE_EXCERPT_MAX' => 250,
  'ZC_COMMENT_EXCERPT_MAX' => 20,
  'ZC_STATIC_MODE' => 'ACTIVE',
  'ZC_ARTICLE_REGEX' => '{%host%}?id={%id%}',
  'ZC_PAGE_REGEX' => '{%host%}?id={%id%}',
  'ZC_CATEGORY_REGEX' => '{%host%}?cate={%id%}&page={%page%}',
  'ZC_AUTHOR_REGEX' => '{%host%}?auth={%id%}&page={%page%}',
  'ZC_TAGS_REGEX' => '{%host%}?tags={%id%}&page={%page%}',
  'ZC_DATE_REGEX' => '{%host%}?date={%date%}&page={%page%}',
  'ZC_INDEX_REGEX' => '{%host%}?page={%page%}',
  'ZC_INDEX_DEFAULT_TEMPLATE' => 'index',
  'ZC_POST_DEFAULT_TEMPLATE' => 'single',
  'ZC_SIDEBAR_ORDER' => 'calendar|controlpanel|catalog|searchpanel|comments|archives|favorite|link|misc',
  'ZC_SIDEBAR2_ORDER' => '',
  'ZC_SIDEBAR3_ORDER' => '',
  'ZC_SIDEBAR4_ORDER' => '',
  'ZC_SIDEBAR5_ORDER' => '',
  'ZC_GZIP_ENABLE' => true,
  'ZC_ADMIN_HTML5_ENABLE' => true,
  'ZC_SYNTAXHIGHLIGHTER_ENABLE' => true,
  'ZC_CODEMIRROR_ENABLE' => true,
  'ZC_HTTP_LASTMODIFIED' => false,
  'ZC_MODULE_CATALOG_STYLE' => 0,
  'ZC_VIEWNUMS_TURNOFF' => false,
  'ZC_LISTONTOP_TURNOFF' => false,
  'ZC_RELATEDLIST_COUNT' => 10,
  'ZC_RUNINFO_DISPLAY' => true,
  'ZC_POST_ALIAS_USE_ID_NOT_TITLE' => false,
)
?>